services:
  nap-web:
    build: 
      context: ./
    networks:
      - web_network
    ports:
      - "127.0.0.1:8080:8080"
  nap-sparql:
    build:
      context: stack/fuseki
    environment:
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ENABLE_DATA_WRITE=false
      - ENABLE_UPDATE=false
      - ENABLE_SHACL=false
    volumes:
      - ./data:/databases:U
    networks:
      - web_network
    x-podman.uidmaps:
        - "0:1:1"
        - "9008:${UID:-1000}:1"
    x-podman.gidmaps:
        - "0:1:1"
        - "9008:${GID:-1000}:1"
networks:
  web_network:
    external: true
    name: web_network
